using UnityEngine;
using System.Collections;

public class BoneGRoot:PieceAnimation
{
public GameObject LARGE_Arm_Back_Lower_01 ;
public GameObject LARGE_Arm_Back_Lower_03 ;
public GameObject LARGE_Arm_Back_Lower_06 ;
public GameObject LARGE_Arm_Back_Lower_07 ;
public GameObject LARGE_Arm_Back_Lower_08 ;
public GameObject LARGE_Arm_Back_Lower_10 ;
public GameObject LARGE_Arm_Back_Upper_01 ;
public GameObject LARGE_Arm_Top_Lower_01  ;
public GameObject LARGE_Arm_Top_Lower_02  ;
public GameObject LARGE_Arm_Top_Lower_03  ;
public GameObject LARGE_Arm_Top_Lower_04  ;
public GameObject LARGE_Arm_Top_Lower_06  ;
public GameObject LARGE_Arm_Top_Lower_07  ;
public GameObject LARGE_Arm_Top_Lower_08  ;
public GameObject LARGE_Arm_Top_Lower_09  ;
public GameObject LARGE_Arm_Top_Lower_10  ;
public GameObject LARGE_Arm_Top_Upper_01  ;
public GameObject LARGE_Head_01           ;
public GameObject LARGE_Head_02           ;
public GameObject LARGE_Head_03           ;
public GameObject LARGE_Head_04           ;
public GameObject LARGE_Head_05           ;
public GameObject LARGE_Head_06           ;
public GameObject LARGE_Head_07           ;
public GameObject LARGE_Head_08           ;
public GameObject LARGE_Head_09           ;
public GameObject LARGE_Head_10           ;
public GameObject LARGE_Head_11           ;
public GameObject LARGE_Head_12           ;
public GameObject LARGE_Head_14           ;
public GameObject LARGE_Leg_Back_Lower_01 ;
public GameObject LARGE_Leg_Back_Upper_01 ;
public GameObject LARGE_Leg_Top_Lower_01  ;
public GameObject LARGE_Leg_Top_Upper_01  ;
public GameObject LARGE_Torso_01          ;
public GameObject Tree_needle_01          ;
public GameObject drop_shadow             ;
public GameObject wildwood_branch_01      ;
public GameObject wildwood_branch_02      ;
public GameObject wildwood_branch_03      ;
public GameObject wildwood_branch_04      ;
	
	
public GameObject Skill15B_Sepaktakraw_02;

public GameObject Skill15B_branch_54;
	public GameObject Skill15B_branch_52;	
	public GameObject Skill15B_branch_56;
	public GameObject Skill15B_branch_58;
	
	
public GameObject LARGE_Head_13           ;
public GameObject LARGE_Arm_Back_Lower_02;
public GameObject LARGE_Arm_Top_Lower_11;
public GameObject LARGE_Arm_Top_Lower_12;
public GameObject LARGE_Arm_Back_Lower_05;
public GameObject LARGE_Leg_Back_Lower_02;
public GameObject LARGE_Leg_Top_Lower_02;
public GameObject LARGE_Torso_03;
public GameObject Skill30B_Tornado_01;
public GameObject Skill30B_Tornado_07;
public GameObject Skill30B_Tornado_09;
public GameObject Skill30B_Tornado_11;
	
	protected override void initPartData ()
	{
		partList = new Hashtable ();
partList ["LARGE_Arm_Back_Lower_01"]=						LARGE_Arm_Back_Lower_01 															;
partList ["LARGE_Arm_Back_Lower_03"]=						LARGE_Arm_Back_Lower_03 															;
partList ["LARGE_Arm_Back_Lower_06"]=						LARGE_Arm_Back_Lower_06 															;
partList ["LARGE_Arm_Back_Lower_07"]=						LARGE_Arm_Back_Lower_07 															;
partList ["LARGE_Arm_Back_Lower_08"]=						LARGE_Arm_Back_Lower_08 															;
partList ["LARGE_Arm_Back_Lower_10"]=						LARGE_Arm_Back_Lower_10 															;
partList ["LARGE_Arm_Back_Upper_01"]=						LARGE_Arm_Back_Upper_01 															;
partList ["LARGE_Arm_Top_Lower_01"]=						LARGE_Arm_Top_Lower_01  															;
partList ["LARGE_Arm_Top_Lower_02"]=						LARGE_Arm_Top_Lower_02  															;
partList ["LARGE_Arm_Top_Lower_022"]=						LARGE_Arm_Top_Lower_02 															;
partList ["LARGE_Arm_Top_Lower_0244"]=					LARGE_Arm_Top_Lower_02														;
partList ["LARGE_Arm_Top_Lower_03"]=						LARGE_Arm_Top_Lower_03  														;
partList ["LARGE_Arm_Top_Lower_04"]=						LARGE_Arm_Top_Lower_04  														;
partList ["LARGE_Arm_Top_Lower_043"]=						LARGE_Arm_Top_Lower_04 																		;
partList ["LARGE_Arm_Top_Lower_06"]=						LARGE_Arm_Top_Lower_06  																	;
partList ["LARGE_Arm_Top_Lower_07"]=						LARGE_Arm_Top_Lower_07  																	;
partList ["LARGE_Arm_Top_Lower_08"]=						LARGE_Arm_Top_Lower_08  																	;
partList ["LARGE_Arm_Top_Lower_09"]=						LARGE_Arm_Top_Lower_09  																	;
partList ["LARGE_Arm_Top_Lower_10"]=						LARGE_Arm_Top_Lower_10  																	;
partList ["LARGE_Arm_Top_Upper_01"]=						LARGE_Arm_Top_Upper_01  																;
partList ["LARGE_Arm_Top_Upper_011"]=						LARGE_Arm_Top_Upper_01 															;
partList ["LARGE_Head_01"]=											LARGE_Head_01           													;
partList ["LARGE_Head_0143"]=										LARGE_Head_01         													;
partList ["LARGE_Head_02"]=											LARGE_Head_02           													;
partList ["LARGE_Head_03"]=											LARGE_Head_03           													;
partList ["LARGE_Head_04"]=											LARGE_Head_04           													;
partList ["LARGE_Head_05"]=											LARGE_Head_05           													;
//partList ["LARGE_Head_06"]=											LARGE_Head_06           													;
partList ["LARGE_Head_07"]=											LARGE_Head_07           													;
partList ["LARGE_Head_08"]=											LARGE_Head_08           													;
partList ["LARGE_Head_09"]=											LARGE_Head_09           													;
partList ["LARGE_Head_10"]=											LARGE_Head_10           													;
partList ["LARGE_Head_11"]=											LARGE_Head_11           													;
partList ["LARGE_Head_12"]=											LARGE_Head_12           													;
partList ["LARGE_Head_14"]=											LARGE_Head_14           													;
partList ["LARGE_Leg_Back_Lower_01"]=						LARGE_Leg_Back_Lower_01 													;
partList ["LARGE_Leg_Back_Lower_011"]=					LARGE_Leg_Back_Lower_01													;
partList ["LARGE_Leg_Back_Upper_01"]=						LARGE_Leg_Back_Upper_01 													;
partList ["LARGE_Leg_Top_Lower_01"]=						LARGE_Leg_Top_Lower_01  													;
partList ["LARGE_Leg_Top_Upper_01"]=						LARGE_Leg_Top_Upper_01  													;
partList ["LARGE_Torso_01"]=										LARGE_Torso_01          													;
partList ["Tree_needle_01"]=										Tree_needle_01          													;
partList ["Tree_needle_011"]=										Tree_needle_01         													;
partList ["Tree_needle_0110"]=									Tree_needle_01        													;
partList ["Tree_needle_0111"]=									Tree_needle_01        													;
partList ["Tree_needle_0112"]=									Tree_needle_01        													;
partList ["Tree_needle_0113"]=									Tree_needle_01        													;
partList ["Tree_needle_0114"]=									Tree_needle_01        													;
partList ["Tree_needle_0115"]=									Tree_needle_01        													;
partList ["Tree_needle_0116"]=									Tree_needle_01        													;
partList ["Tree_needle_0117"]=									Tree_needle_01        													;
partList ["Tree_needle_0118"]=									Tree_needle_01        													;
partList ["Tree_needle_0119"]=									Tree_needle_01        													;
partList ["Tree_needle_012"]=										Tree_needle_01         													;
partList ["Tree_needle_0120"]=									Tree_needle_01        													;
partList ["Tree_needle_0121"]=									Tree_needle_01        													;
partList ["Tree_needle_0122"]=									Tree_needle_01        													;
partList ["Tree_needle_0123"]=									Tree_needle_01        													;
partList ["Tree_needle_0124"]=									Tree_needle_01        													;
partList ["Tree_needle_0125"]=									Tree_needle_01        													;
partList ["Tree_needle_0126"]=									Tree_needle_01        													;
partList ["Tree_needle_0127"]=									Tree_needle_01        													;
partList ["Tree_needle_0128"]=									Tree_needle_01        													;
partList ["Tree_needle_0129"]=									Tree_needle_01        													;
partList ["Tree_needle_013"]=										Tree_needle_01         													;
partList ["Tree_needle_0130"]=									Tree_needle_01        													;
partList ["Tree_needle_0131"]=									Tree_needle_01        													;
partList ["Tree_needle_0132"]=									Tree_needle_01        													;
partList ["Tree_needle_0133"]=									Tree_needle_01        													;
partList ["Tree_needle_0134"]=									Tree_needle_01        													;
partList ["Tree_needle_0135"]=									Tree_needle_01        													;
partList ["Tree_needle_014"]=										Tree_needle_01         													;																						
partList ["Tree_needle_015"]=										Tree_needle_01         													;
partList ["Tree_needle_016"]=										Tree_needle_01         													;
partList ["Tree_needle_017"]=										Tree_needle_01         													;
partList ["Tree_needle_018"]=										Tree_needle_01         													;
partList ["Tree_needle_019"]=										Tree_needle_01         													;
partList ["drop_shadow"]=												drop_shadow             													;
partList ["wildwood_branch_01"]=								wildwood_branch_01      													;
partList ["wildwood_branch_0136"]=							wildwood_branch_01    													;
partList ["wildwood_branch_0137"]=							wildwood_branch_01    													;
partList ["wildwood_branch_0138"]=							wildwood_branch_01    													;
partList ["wildwood_branch_0139"]=							wildwood_branch_01    													;
partList ["wildwood_branch_0142"]=							wildwood_branch_01    													;
partList ["wildwood_branch_0147"]=							wildwood_branch_01    													;
partList ["wildwood_branch_0148"]=							wildwood_branch_01    													;
partList ["wildwood_branch_0149"]=							wildwood_branch_01    													;
partList ["wildwood_branch_0150"]=							wildwood_branch_01    													;
partList ["wildwood_branch_02"]=								wildwood_branch_02      													; 																				
partList ["wildwood_branch_0241"]=							wildwood_branch_02    													;
partList ["wildwood_branch_0245"]=							wildwood_branch_02    													;
partList ["wildwood_branch_0246"]=							wildwood_branch_02    													;
partList ["wildwood_branch_0251"]=							wildwood_branch_02    													;
partList ["wildwood_branch_0252"]=							wildwood_branch_02    													;
partList ["wildwood_branch_03"]=								wildwood_branch_03      													;
partList ["wildwood_branch_0340"]=							wildwood_branch_03    													;
partList ["wildwood_branch_04"]=								wildwood_branch_04      													;
		
		partList ["Skill15B_Sepaktakraw_02"]=							Skill15B_Sepaktakraw_02    													;
partList ["Skill15B_branch_52"]=							Skill15B_branch_52    													;
partList ["Skill15B_branch_54"]=								Skill15B_branch_54      													;
partList ["Skill15B_branch_56"]=							Skill15B_branch_56    													;
partList ["Skill15B_branch_58"]=								Skill15B_branch_58      													;

					  partList ["LARGE_Arm_Back_Lower_02"] =   LARGE_Arm_Back_Lower_02;
			  partList ["LARGE_Arm_Back_Lower_05"] =   LARGE_Arm_Back_Lower_05;
			  partList ["LARGE_Arm_Back_Upper_018"] =  LARGE_Arm_Back_Upper_01; 
			  partList ["LARGE_Arm_Top_Lower_11"] =    LARGE_Arm_Top_Lower_11;
			  partList ["LARGE_Arm_Top_Lower_12"] =    LARGE_Arm_Top_Lower_12;
			  partList ["LARGE_Arm_Top_Upper_014"] =   LARGE_Arm_Top_Upper_01;
			  partList ["LARGE_Leg_Back_Lower_02"] =   LARGE_Leg_Back_Lower_02;
			  partList ["LARGE_Leg_Back_Upper_017"] =  LARGE_Leg_Back_Upper_01;
			  partList ["LARGE_Leg_Back_Upper_019"] =  LARGE_Leg_Back_Upper_01;
			  partList ["LARGE_Leg_Top_Lower_016"] =   LARGE_Leg_Top_Lower_01;
			  partList ["LARGE_Leg_Top_Lower_02"] =    LARGE_Leg_Top_Lower_02;
			  partList ["LARGE_Leg_Top_Upper_012"] =   LARGE_Leg_Top_Upper_01;
			  partList ["LARGE_Leg_Top_Upper_015"] =   LARGE_Leg_Top_Upper_01;
			  partList ["LARGE_Torso_03"] =            LARGE_Torso_03;
			  partList ["Skill30B_Tornado_01"] =                Skill30B_Tornado_01;
			  partList ["Skill30B_Tornado_07"] =                Skill30B_Tornado_07;
			  partList ["Skill30B_Tornado_09"] =                Skill30B_Tornado_09;
			  partList ["Skill30B_Tornado_11"] =                Skill30B_Tornado_11;
		partList ["LARGE_Head_13"]=											LARGE_Head_13           													;
		partList ["LARGE_Arm_Top_Lower_023"]=											LARGE_Arm_Top_Lower_02           													;
		
	}
}