using UnityEngine;
using System.Collections;

public class BoneCharlie27 : PieceAnimation
{
//    public GameObject LARGE_Arm_Back_Lower_01  ;
//    public GameObject LARGE_Arm_Back_Lower_04  ;
//    public GameObject LARGE_Arm_Back_Lower_05  ;
//    public GameObject LARGE_Arm_Back_Upper_01  ;
//    public GameObject LARGE_Arm_Back_Upper_02  ;
//    public GameObject LARGE_Arm_Back_Upper_03  ;
//    public GameObject LARGE_Arm_Top_Lower_01   ;
//    public GameObject LARGE_Arm_Top_Lower_02   ;
//    public GameObject LARGE_Arm_Top_Lower_03   ;
//    public GameObject LARGE_Arm_Top_Lower_04   ;
//    public GameObject LARGE_Arm_Top_Lower_05   ;
//    public GameObject LARGE_Arm_Top_Lower_06   ;
//    public GameObject LARGE_Arm_Top_Lower_07   ;
//    public GameObject LARGE_Arm_Top_Lower_08   ;
//    public GameObject LARGE_Arm_Top_Lower_09   ;
//    public GameObject LARGE_Arm_Top_Lower_10   ;
//    public GameObject LARGE_Arm_Top_Lower_11   ;
//    public GameObject LARGE_Arm_Top_Upper_01   ;
//    public GameObject LARGE_Arm_Top_Upper_02   ;
//    public GameObject LARGE_Arm_Top_Upper_03   ;
//    public GameObject LARGE_Arm_Top_Upper_04   ;
//    public GameObject LARGE_Head_01            ;
//    public GameObject LARGE_Head_02            ;
//    public GameObject LARGE_Head_03            ;
//    public GameObject LARGE_Head_04            ;
//    public GameObject LARGE_Head_05            ;
//    public GameObject LARGE_Leg_Back_Lower_01  ;
//    public GameObject LARGE_Leg_Back_Lower_02  ;
//    public GameObject LARGE_Leg_Back_Upper_01  ;
//    public GameObject LARGE_Leg_Back_Upper_02  ;
//    public GameObject LARGE_Leg_Top_Lower_01   ;
//    public GameObject LARGE_Leg_Top_Lower_02   ;
//    public GameObject LARGE_Leg_Top_Upper_01   ;
//    public GameObject LARGE_Leg_Top_Upper_02   ;
//    public GameObject LARGE_Torso_01           ;
//    public GameObject LARGE_Torso_02           ;
//    public GameObject LARGE_Torso_03           ;
//    public GameObject LARGE_Torso_04           ;
//    public GameObject drop_shadow              ;
	
    public GameObject Antitank_grenade_01    ;
    public GameObject Antitank_grenade_04    ;
    public GameObject LARGE_Arm_Back_Lower_01;
    public GameObject LARGE_Arm_Back_Lower_02;
    public GameObject LARGE_Arm_Back_Lower_03;
    public GameObject LARGE_Arm_Back_Lower_04;
    public GameObject LARGE_Arm_Back_Lower_05;
    public GameObject LARGE_Arm_Back_Upper_01;
    public GameObject LARGE_Arm_Back_Upper_02;
    public GameObject LARGE_Arm_Back_Upper_03;
    public GameObject LARGE_Arm_Top_Lower_01 ;
    public GameObject LARGE_Arm_Top_Lower_02 ;
    public GameObject LARGE_Arm_Top_Lower_03 ;
    public GameObject LARGE_Arm_Top_Lower_04 ;
    public GameObject LARGE_Arm_Top_Lower_05 ;
    public GameObject LARGE_Arm_Top_Lower_06 ;
    public GameObject LARGE_Arm_Top_Lower_07 ;
    public GameObject LARGE_Arm_Top_Lower_08 ;
    public GameObject LARGE_Arm_Top_Lower_09 ;
    public GameObject LARGE_Arm_Top_Lower_10 ;
    public GameObject LARGE_Arm_Top_Lower_11 ;
    public GameObject LARGE_Arm_Top_Lower_12 ;
    public GameObject LARGE_Arm_Top_Upper_01 ;
    public GameObject LARGE_Arm_Top_Upper_02 ;
    public GameObject LARGE_Arm_Top_Upper_03 ;
    public GameObject LARGE_Arm_Top_Upper_04 ;
    public GameObject LARGE_Head_01          ;
    public GameObject LARGE_Head_02          ;
    public GameObject LARGE_Head_03          ;
    public GameObject LARGE_Head_04          ;
    public GameObject LARGE_Head_05          ;
    public GameObject LARGE_Leg_Back_Lower_01;
    public GameObject LARGE_Leg_Back_Lower_02;
    public GameObject LARGE_Leg_Back_Upper_01;
    public GameObject LARGE_Leg_Back_Upper_02;
    public GameObject LARGE_Leg_Top_Lower_01 ;
    public GameObject LARGE_Leg_Top_Lower_02 ;
    public GameObject LARGE_Leg_Top_Upper_01 ;
    public GameObject LARGE_Leg_Top_Upper_02 ;
    public GameObject LARGE_Torso_01         ;
    public GameObject LARGE_Torso_02         ;
    public GameObject LARGE_Torso_03         ;
    public GameObject LARGE_Torso_04         ;
    public GameObject drop_shadow            ;	
	
	public override void Awake ()
	{
		base.Awake ();
	}
	
	// Update is called once per frame
	protected override void initPartData ()
	{
		partList = new Hashtable ();
		
        partList["Antitank_grenade_01"       ] = Antitank_grenade_01    ;
        partList["Antitank_grenade_04"       ] = Antitank_grenade_04    ;
        partList["Antitank_grenade_04__2"    ] = Antitank_grenade_04    ;
        partList["LARGE_Arm_Back_Lower_01"   ] = LARGE_Arm_Back_Lower_01;
        partList["LARGE_Arm_Back_Lower_01__1"] = LARGE_Arm_Back_Lower_01;
        partList["LARGE_Arm_Back_Lower_01__3"] = LARGE_Arm_Back_Lower_01;
        partList["LARGE_Arm_Back_Lower_02"   ] = LARGE_Arm_Back_Lower_02;
        partList["LARGE_Arm_Back_Lower_02__1"] = LARGE_Arm_Back_Lower_02;
        partList["LARGE_Arm_Back_Lower_03"   ] = LARGE_Arm_Back_Lower_03;
        partList["LARGE_Arm_Back_Lower_04"   ] = LARGE_Arm_Back_Lower_04;
        partList["LARGE_Arm_Back_Lower_05"   ] = LARGE_Arm_Back_Lower_05;
        partList["LARGE_Arm_Back_Upper_01"   ] = LARGE_Arm_Back_Upper_01;
        partList["LARGE_Arm_Back_Upper_02"   ] = LARGE_Arm_Back_Upper_02;
        partList["LARGE_Arm_Back_Upper_03"   ] = LARGE_Arm_Back_Upper_03;
        partList["LARGE_Arm_Top_Lower_01"    ] = LARGE_Arm_Top_Lower_01 ;
        partList["LARGE_Arm_Top_Lower_02"    ] = LARGE_Arm_Top_Lower_02 ;
        partList["LARGE_Arm_Top_Lower_03"    ] = LARGE_Arm_Top_Lower_03 ;
        partList["LARGE_Arm_Top_Lower_04"    ] = LARGE_Arm_Top_Lower_04 ;
        partList["LARGE_Arm_Top_Lower_05"    ] = LARGE_Arm_Top_Lower_05 ;
        partList["LARGE_Arm_Top_Lower_06"    ] = LARGE_Arm_Top_Lower_06 ;
        partList["LARGE_Arm_Top_Lower_07"    ] = LARGE_Arm_Top_Lower_07 ;
        partList["LARGE_Arm_Top_Lower_08"    ] = LARGE_Arm_Top_Lower_08 ;
        partList["LARGE_Arm_Top_Lower_08__1" ] = LARGE_Arm_Top_Lower_08 ;
        partList["LARGE_Arm_Top_Lower_09"    ] = LARGE_Arm_Top_Lower_09 ;
        partList["LARGE_Arm_Top_Lower_10"    ] = LARGE_Arm_Top_Lower_10 ;
        partList["LARGE_Arm_Top_Lower_11"    ] = LARGE_Arm_Top_Lower_11 ;
        partList["LARGE_Arm_Top_Lower_12"    ] = LARGE_Arm_Top_Lower_12 ;
        partList["LARGE_Arm_Top_Upper_01"    ] = LARGE_Arm_Top_Upper_01 ;
        partList["LARGE_Arm_Top_Upper_02"    ] = LARGE_Arm_Top_Upper_02 ;
        partList["LARGE_Arm_Top_Upper_03"    ] = LARGE_Arm_Top_Upper_03 ;
        partList["LARGE_Arm_Top_Upper_04"    ] = LARGE_Arm_Top_Upper_04 ;
        partList["LARGE_Head_01"             ] = LARGE_Head_01          ;
        partList["LARGE_Head_02"             ] = LARGE_Head_02          ;
        partList["LARGE_Head_03"             ] = LARGE_Head_03          ;
        partList["LARGE_Head_04"             ] = LARGE_Head_04          ;
        partList["LARGE_Head_05"             ] = LARGE_Head_05          ;
        partList["LARGE_Leg_Back_Lower_01"   ] = LARGE_Leg_Back_Lower_01;
        partList["LARGE_Leg_Back_Lower_02"   ] = LARGE_Leg_Back_Lower_02;
        partList["LARGE_Leg_Back_Upper_01"   ] = LARGE_Leg_Back_Upper_01;
        partList["LARGE_Leg_Back_Upper_02"   ] = LARGE_Leg_Back_Upper_02;
        partList["LARGE_Leg_Top_Lower_01"    ] = LARGE_Leg_Top_Lower_01 ;
        partList["LARGE_Leg_Top_Lower_02"    ] = LARGE_Leg_Top_Lower_02 ;
        partList["LARGE_Leg_Top_Upper_01"    ] = LARGE_Leg_Top_Upper_01 ;
        partList["LARGE_Leg_Top_Upper_02"    ] = LARGE_Leg_Top_Upper_02 ;
        partList["LARGE_Torso_01"            ] = LARGE_Torso_01         ;
        partList["LARGE_Torso_02"            ] = LARGE_Torso_02         ;
        partList["LARGE_Torso_02__1"         ] = LARGE_Torso_02         ;
        partList["LARGE_Torso_03"            ] = LARGE_Torso_03         ;
        partList["LARGE_Torso_04"            ] = LARGE_Torso_04         ;
        partList["drop_shadow"               ] = drop_shadow            ;		
		
//        partList["LARGE_Arm_Back_Lower_01"  ] = LARGE_Arm_Back_Lower_01  ;
//        partList["LARGE_Arm_Back_Lower_04"  ] = LARGE_Arm_Back_Lower_04  ;
//        partList["LARGE_Arm_Back_Lower_05"  ] = LARGE_Arm_Back_Lower_05  ;
//        partList["LARGE_Arm_Back_Upper_01"  ] = LARGE_Arm_Back_Upper_01  ;
//        partList["LARGE_Arm_Back_Upper_02"  ] = LARGE_Arm_Back_Upper_02  ;
//        partList["LARGE_Arm_Back_Upper_03"  ] = LARGE_Arm_Back_Upper_03  ;
//        partList["LARGE_Arm_Top_Lower_01"   ] = LARGE_Arm_Top_Lower_01   ;
//        partList["LARGE_Arm_Top_Lower_02"   ] = LARGE_Arm_Top_Lower_02   ;
//        partList["LARGE_Arm_Top_Lower_03"   ] = LARGE_Arm_Top_Lower_03   ;
//        partList["LARGE_Arm_Top_Lower_04"   ] = LARGE_Arm_Top_Lower_04   ;
//        partList["LARGE_Arm_Top_Lower_05"   ] = LARGE_Arm_Top_Lower_05   ;
//        partList["LARGE_Arm_Top_Lower_06"   ] = LARGE_Arm_Top_Lower_06   ;
//        partList["LARGE_Arm_Top_Lower_07"   ] = LARGE_Arm_Top_Lower_07   ;
//        partList["LARGE_Arm_Top_Lower_08"   ] = LARGE_Arm_Top_Lower_08   ;
//        partList["LARGE_Arm_Top_Lower_08__1"] = LARGE_Arm_Top_Lower_08   ;
//        partList["LARGE_Arm_Top_Lower_09"   ] = LARGE_Arm_Top_Lower_09   ;
//        partList["LARGE_Arm_Top_Lower_10"   ] = LARGE_Arm_Top_Lower_10   ;
//        partList["LARGE_Arm_Top_Lower_11"   ] = LARGE_Arm_Top_Lower_11   ;
//        partList["LARGE_Arm_Top_Upper_01"   ] = LARGE_Arm_Top_Upper_01   ;
//        partList["LARGE_Arm_Top_Upper_02"   ] = LARGE_Arm_Top_Upper_02   ;
//        partList["LARGE_Arm_Top_Upper_03"   ] = LARGE_Arm_Top_Upper_03   ;
//        partList["LARGE_Arm_Top_Upper_04"   ] = LARGE_Arm_Top_Upper_04   ;
//        partList["LARGE_Head_01"            ] = LARGE_Head_01            ;
//        partList["LARGE_Head_02"            ] = LARGE_Head_02            ;
//        partList["LARGE_Head_03"            ] = LARGE_Head_03            ;
//        partList["LARGE_Head_04"            ] = LARGE_Head_04            ;
//        partList["LARGE_Head_05"            ] = LARGE_Head_05            ;
//        partList["LARGE_Leg_Back_Lower_01"  ] = LARGE_Leg_Back_Lower_01  ;
//        partList["LARGE_Leg_Back_Lower_02"  ] = LARGE_Leg_Back_Lower_02  ;
//        partList["LARGE_Leg_Back_Upper_01"  ] = LARGE_Leg_Back_Upper_01  ;
//        partList["LARGE_Leg_Back_Upper_02"  ] = LARGE_Leg_Back_Upper_02  ;
//        partList["LARGE_Leg_Top_Lower_01"   ] = LARGE_Leg_Top_Lower_01   ;
//        partList["LARGE_Leg_Top_Lower_02"   ] = LARGE_Leg_Top_Lower_02   ;
//        partList["LARGE_Leg_Top_Upper_01"   ] = LARGE_Leg_Top_Upper_01   ;
//        partList["LARGE_Leg_Top_Upper_02"   ] = LARGE_Leg_Top_Upper_02   ;
//        partList["LARGE_Torso_01"           ] = LARGE_Torso_01           ;
//        partList["LARGE_Torso_02"           ] = LARGE_Torso_02           ;
//        partList["LARGE_Torso_02__1"        ] = LARGE_Torso_02           ;
//        partList["LARGE_Torso_03"           ] = LARGE_Torso_03           ;
//        partList["LARGE_Torso_04"           ] = LARGE_Torso_04           ;
//        partList["drop_shadow"              ] = drop_shadow              ;		
//		
//        partList["LARGE_Arm_Back_Lower_01"] = LARGE_Arm_Back_Lower_01;
//        partList["LARGE_Arm_Back_Lower_04"] = LARGE_Arm_Back_Lower_04;
//        partList["LARGE_Arm_Back_Lower_05"] = LARGE_Arm_Back_Lower_05;
//        partList["LARGE_Arm_Back_Upper_01"] = LARGE_Arm_Back_Upper_01;
//        partList["LARGE_Arm_Back_Upper_02"] = LARGE_Arm_Back_Upper_02;
//        partList["LARGE_Arm_Back_Upper_03"] = LARGE_Arm_Back_Upper_03;
//        partList["LARGE_Arm_Top_Lower_01" ] = LARGE_Arm_Top_Lower_01 ;
//        partList["LARGE_Arm_Top_Lower_02" ] = LARGE_Arm_Top_Lower_02 ;
//        partList["LARGE_Arm_Top_Lower_03" ] = LARGE_Arm_Top_Lower_03 ;
//        partList["LARGE_Arm_Top_Lower_04" ] = LARGE_Arm_Top_Lower_04 ;
//        partList["LARGE_Arm_Top_Lower_06" ] = LARGE_Arm_Top_Lower_06 ;
//        partList["LARGE_Arm_Top_Upper_01" ] = LARGE_Arm_Top_Upper_01 ;
//        partList["LARGE_Arm_Top_Upper_02" ] = LARGE_Arm_Top_Upper_02 ;
//        partList["LARGE_Arm_Top_Upper_03" ] = LARGE_Arm_Top_Upper_03 ;
//        partList["LARGE_Arm_Top_Upper_04" ] = LARGE_Arm_Top_Upper_04 ;
//        partList["LARGE_Head_01"          ] = LARGE_Head_01          ;
//        partList["LARGE_Head_02"          ] = LARGE_Head_02          ;
//        partList["LARGE_Head_03"          ] = LARGE_Head_03          ;
//        partList["LARGE_Head_04"          ] = LARGE_Head_04          ;
//        partList["LARGE_Head_05"          ] = LARGE_Head_05          ;
//        partList["LARGE_Leg_Back_Lower_01"] = LARGE_Leg_Back_Lower_01;
//        partList["LARGE_Leg_Back_Lower_02"] = LARGE_Leg_Back_Lower_02;
//        partList["LARGE_Leg_Back_Upper_01"] = LARGE_Leg_Back_Upper_01;
//        partList["LARGE_Leg_Back_Upper_02"] = LARGE_Leg_Back_Upper_02;
//        partList["LARGE_Leg_Top_Lower_01" ] = LARGE_Leg_Top_Lower_01 ;
//        partList["LARGE_Leg_Top_Lower_02" ] = LARGE_Leg_Top_Lower_02 ;
//        partList["LARGE_Leg_Top_Upper_01" ] = LARGE_Leg_Top_Upper_01 ;
//        partList["LARGE_Leg_Top_Upper_02" ] = LARGE_Leg_Top_Upper_02 ;
//        partList["LARGE_Torso_01"         ] = LARGE_Torso_01         ;
//        partList["LARGE_Torso_02"         ] = LARGE_Torso_02         ;
//        partList["LARGE_Torso_02__1"      ] = LARGE_Torso_02         ;
//        partList["LARGE_Torso_03"         ] = LARGE_Torso_03         ;
//        partList["LARGE_Torso_04"         ] = LARGE_Torso_04         ;
//        partList["drop_shadow"            ] = drop_shadow            ;
	}
}
