using UnityEngine;
using System.Collections;


public class BoneRocket : PieceAnimation {
	
//	public GameObject Prop_01;                
//	public GameObject Prop_02;                
//	public GameObject Prop_03;                
//	public GameObject Prop_04;                
//	public GameObject Prop_05;                
//	public GameObject SpecialEffects_01;      
//	public GameObject SpecialEffects_84;      
//	public GameObject SpecialEffects_85;      
//	public GameObject TINY_Arm_Back_Lower_01; 
//	public GameObject TINY_Arm_Back_Upper_01; 
//	public GameObject TINY_Arm_Top_Lower_01;  
//	public GameObject TINY_Arm_Top_Lower_02;  
//	public GameObject TINY_Arm_Top_Upper_01;  
//	public GameObject TINY_Head_01;           
//	public GameObject TINY_Head_02;           
//	public GameObject TINY_Head_03;           
//	public GameObject TINY_Head_04;           
//	public GameObject TINY_Head_05;           
//	public GameObject TINY_Leg_Back_Lower_01; 
//	public GameObject TINY_Leg_Back_Lower_02; 
//	public GameObject TINY_Leg_Back_Upper_01; 
//	public GameObject TINY_Leg_Top_Lower_01;  
//	public GameObject TINY_Leg_Top_Lower_02;  
//	public GameObject TINY_Leg_Top_Upper_01;  
//	public GameObject TINY_Tail_01;           
//	public GameObject TINY_Torso_01;          
//	public GameObject TINY_Torso_02;          
//	public GameObject TINY_Weapon_01;         
//	public GameObject TINY_Weapon_02;         
//	public GameObject TINY_Weapon_03;         
//	public GameObject TINY_Weapon_04;         
//	public GameObject TINY_Weapon_05;         
//	public GameObject drop_shadow;  
	
//	public GameObject Antitank_Grenade_02;
//	public GameObject Prop_01;
//	public GameObject Prop_02;
//	public GameObject Prop_03;
//	public GameObject Prop_04;
//	public GameObject Prop_05;
//	public GameObject Prop_06;
//	public GameObject Prop_07;
//	public GameObject Prop_08;
//	public GameObject Prop_09;
//	public GameObject Special_Effects_84;
//	public GameObject TINY_Arm_Back_Lower_01;
//	public GameObject TINY_Arm_Back_Upper_01;
//	public GameObject TINY_Arm_Top_Lower_01;
//	public GameObject TINY_Arm_Top_Lower_02;
//	public GameObject TINY_Arm_Top_Lower_03;
//	public GameObject TINY_Arm_Top_Lower_04;
//	public GameObject TINY_Arm_Top_Upper_01;
//	public GameObject TINY_Head_01;
//	public GameObject TINY_Head_02;
//	public GameObject TINY_Head_03;
//	public GameObject TINY_Head_04;
//	public GameObject TINY_Head_05;
//	public GameObject TINY_Leg_Back_Lower_01;
//	public GameObject TINY_Leg_Back_Lower_02;
//	public GameObject TINY_Leg_Back_Upper_01;
//	public GameObject TINY_Leg_Top_Lower_01;
//	public GameObject TINY_Leg_Top_Lower_02;
//	public GameObject TINY_Leg_Top_Upper_01;
//	public GameObject TINY_Tail_01;
//	public GameObject TINY_Torso_01;
//	public GameObject TINY_Torso_02;
//	public GameObject TINY_Weapon_01;
//	public GameObject TINY_Weapon_02;
//	public GameObject TINY_Weapon_03;
//	public GameObject TINY_Weapon_04;
//	public GameObject TINY_Weapon_05;
//	public GameObject TINY_Weapon_06;
//	public GameObject TINY_Weapon_07;
//	public GameObject TINY_Weapon_08;
//	public GameObject TINY_Weapon_09;
//	public GameObject drop_shadow;
//		public GameObject Antitank_grenade_03;
//public GameObject Special_effects_125;
//public GameObject Special_effects_127;
	
	public GameObject Antitank_grenade_02                                  ;
	public GameObject Antitank_grenade_03                                  ;
	public GameObject JAR_D                                  ;
	public GameObject Jar                                  ;
	public GameObject Jar_a                                  ;
	public GameObject Jar_b                                  ;
	public GameObject Jar_c                                  ;
	public GameObject Light2_1a                                  ;
	public GameObject Prop_01                                  ;
	public GameObject Prop_02                                  ;
	public GameObject Prop_03                                  ;
	public GameObject Prop_04                                  ;
	public GameObject Prop_05                                  ;
	public GameObject Prop_06                                  ;
	public GameObject Prop_07                                  ;
	public GameObject Prop_08                                  ;
	public GameObject Prop_09                                  ;
	public GameObject SpecialEffects_84                                  ;
	public GameObject Special_effects_125                                  ;
	public GameObject Special_effects_127                                  ;
	public GameObject Special_effects_160                                  ;
	public GameObject Special_effects_161                                  ;
	public GameObject Special_effects_162                                  ;
	public GameObject TINY_Arm_Back_Lower_01                                  ;
	public GameObject TINY_Arm_Back_Lower_02                                  ;
	public GameObject TINY_Arm_Back_Upper_01                                  ;
	public GameObject TINY_Arm_Top_Lower_01                                  ;
	public GameObject TINY_Arm_Top_Lower_02                                  ;
	public GameObject TINY_Arm_Top_Lower_03                                  ;
	public GameObject TINY_Arm_Top_Lower_04                                  ;
	public GameObject TINY_Arm_Top_Upper_01                                  ;
	public GameObject TINY_Head_01                                  ;
	public GameObject TINY_Head_02                                  ;
	public GameObject TINY_Head_03                                  ;
	public GameObject TINY_Head_04                                  ;
	public GameObject TINY_Head_05                                  ;
	public GameObject TINY_Leg_Back_Lower_01                                  ;
	public GameObject TINY_Leg_Back_Lower_02                                  ;
	public GameObject TINY_Leg_Back_Upper_01                                  ;
	public GameObject TINY_Leg_Top_Lower_01                                  ;
	public GameObject TINY_Leg_Top_Lower_02                                  ;
	public GameObject TINY_Leg_Top_Upper_01                                  ;
	public GameObject TINY_Tail_01                                  ;
	public GameObject TINY_Torso_01                                  ;
	public GameObject TINY_Torso_02                                  ;
	public GameObject TINY_Weapon_01                                  ; 
	public GameObject TINY_Weapon_02                                  ;
	public GameObject TINY_Weapon_03                                  ;
	public GameObject TINY_Weapon_04                                  ;
	public GameObject TINY_Weapon_05                                  ;
	public GameObject TINY_Weapon_06                                  ;
	public GameObject TINY_Weapon_07                                  ;
	public GameObject TINY_Weapon_08                                  ;
	public GameObject TINY_Weapon_09                                  ;
	public GameObject TINY_Weapon_10                                  ;
	public GameObject drop_shadow                                  ;
	
	
	public override void Awake () {
		base.Awake();
	}
	
	protected override void initPartData ()
	{
		partList = new Hashtable();
//		partList["Prop_01"                ]= Prop_01;                
//		partList["Prop_02"                ]= Prop_02;                
//		partList["Prop_022"               ]= Prop_02;               
//		partList["Prop_023"               ]= Prop_02;               
//		partList["Prop_03"                ]= Prop_03;                
//		partList["Prop_04"                ]= Prop_04;                
//		partList["Prop_05"                ]= Prop_05;                
//		partList["SpecialEffects_01"      ]= SpecialEffects_01;      
//		partList["SpecialEffects_84"      ]= SpecialEffects_84;      
//		partList["SpecialEffects_842"     ]= SpecialEffects_84;     
//		partList["SpecialEffects_85"      ]= SpecialEffects_85;      
//		partList["TINY_Arm_Back_Lower_01" ]= TINY_Arm_Back_Lower_01; 
//		partList["TINY_Arm_Back_Lower_016"]= TINY_Arm_Back_Lower_01;
//		partList["TINY_Arm_Back_Upper_01" ]= TINY_Arm_Back_Upper_01; 
//		partList["TINY_Arm_Back_Upper_015"]= TINY_Arm_Back_Upper_01;
//		partList["TINY_Arm_Top_Lower_01"  ]= TINY_Arm_Top_Lower_01;  
//		partList["TINY_Arm_Top_Lower_011" ]= TINY_Arm_Top_Lower_01; 
//		partList["TINY_Arm_Top_Lower_013" ]= TINY_Arm_Top_Lower_01; 
//		partList["TINY_Arm_Top_Lower_02"  ]= TINY_Arm_Top_Lower_02;  
//		partList["TINY_Arm_Top_Upper_01"  ]= TINY_Arm_Top_Upper_01;  
//		partList["TINY_Head_01"           ]= TINY_Head_01;           
//		partList["TINY_Head_02"           ]= TINY_Head_02;           
//		partList["TINY_Head_03"           ]= TINY_Head_03;           
//		partList["TINY_Head_04"           ]= TINY_Head_04;           
//		partList["TINY_Head_05"           ]= TINY_Head_05;           
//		partList["TINY_Leg_Back_Lower_01" ]= TINY_Leg_Back_Lower_01; 
//		partList["TINY_Leg_Back_Lower_02" ]= TINY_Leg_Back_Lower_02; 
//		partList["TINY_Leg_Back_Upper_01" ]= TINY_Leg_Back_Upper_01; 
//		partList["TINY_Leg_Top_Lower_01"  ]= TINY_Leg_Top_Lower_01;  
//		partList["TINY_Leg_Top_Lower_02"  ]= TINY_Leg_Top_Lower_02;  
//		partList["TINY_Leg_Top_Upper_01"  ]= TINY_Leg_Top_Upper_01;  
//		partList["TINY_Tail_01"           ]= TINY_Tail_01;           
//		partList["TINY_Torso_01"          ]= TINY_Torso_01;          
//		partList["TINY_Torso_02"          ]= TINY_Torso_02;          
//		partList["TINY_Weapon_01"         ]= TINY_Weapon_01;         
//		partList["TINY_Weapon_02"         ]= TINY_Weapon_02;         
//		partList["TINY_Weapon_0210"       ]= TINY_Weapon_02;       
//		partList["TINY_Weapon_024"        ]= TINY_Weapon_02;        
//		partList["TINY_Weapon_03"         ]= TINY_Weapon_03;         
//		partList["TINY_Weapon_0311"       ]= TINY_Weapon_03;       
//		partList["TINY_Weapon_037"        ]= TINY_Weapon_03;        
//		partList["TINY_Weapon_04"         ]= TINY_Weapon_04;         
//		partList["TINY_Weapon_048"        ]= TINY_Weapon_04;        
//		partList["TINY_Weapon_05"         ]= TINY_Weapon_05;         
//		partList["TINY_Weapon_059"        ]= TINY_Weapon_05;        
//		partList["drop_shadow"            ]= drop_shadow;            

        partList["Antitank_grenade_02"         ]=  Antitank_grenade_02         ;               
		partList["Antitank_grenade_03"        ]=  Antitank_grenade_03        ;                      
		partList["Antitank_grenade_03__49"    ]=  Antitank_grenade_03    ;                          
		partList["Antitank_grenade_03__51"    ]=  Antitank_grenade_03    ;                          
		partList["Antitank_grenade_03__53"    ]=  Antitank_grenade_03    ;                          
		partList["JAR_D"                      ]=  JAR_D                      ;        
		partList["Jar"                        ]=  Jar                        ;      
		partList["Jar_a"                      ]=  Jar_a                      ;        
		partList["Jar_b"                      ]=  Jar_b                      ;        
		partList["Jar_c"                      ]=  Jar_c                      ;        
		partList["Light2_1a"                  ]=  Light2_1a                  ;            
		partList["Light2_1a__1"               ]=  Light2_1a               ;               
		partList["Prop_01"                    ]=  Prop_01                    ;          
		partList["Prop_02"                    ]=  Prop_02                    ;          
		partList["Prop_02__2"                 ]=  Prop_02                 ;             
		partList["Prop_02__3"                 ]=  Prop_02                 ;             
		partList["Prop_03"                    ]=  Prop_03                    ;          
		partList["Prop_04"                    ]=  Prop_04                    ;          
		partList["Prop_05"                    ]=  Prop_05                    ;          
		partList["Prop_06"                    ]=  Prop_06                    ;          
		partList["Prop_06__1"                 ]=  Prop_06                 ;             
		partList["Prop_06__3"                 ]=  Prop_06                 ;             
		partList["Prop_06__4"                 ]=  Prop_06                 ;             
		partList["Prop_07"                    ]=  Prop_07                    ;          
		partList["Prop_08"                    ]=  Prop_08                    ;          
		partList["Prop_09"                    ]=  Prop_09                    ;          
		partList["SpecialEffects_84"          ]=  SpecialEffects_84          ;                    
		partList["SpecialEffects_84__2"       ]=  SpecialEffects_84       ;                       
		partList["Special_effects_125"        ]=  Special_effects_125        ;                      
		partList["Special_effects_125__43"    ]=  Special_effects_125    ;                          
		partList["Special_effects_125__44"    ]=  Special_effects_125    ;                          
		partList["Special_effects_127"        ]=  Special_effects_127        ;                      
		partList["Special_effects_127__1"     ]=  Special_effects_127     ;                         
		partList["Special_effects_127__10"    ]=  Special_effects_127    ;                          
		partList["Special_effects_127__11"    ]=  Special_effects_127    ;                          
		partList["Special_effects_127__12"    ]=  Special_effects_127    ;                          
		partList["Special_effects_127__13"    ]=  Special_effects_127    ;                          
		partList["Special_effects_127__14"    ]=  Special_effects_127    ;                          
		partList["Special_effects_127__15"    ]=  Special_effects_127    ;                          
		partList["Special_effects_127__16"    ]=  Special_effects_127    ;                          
		partList["Special_effects_127__17"    ]=  Special_effects_127    ;                          
		partList["Special_effects_127__18"    ]=  Special_effects_127    ;                          
		partList["Special_effects_127__19"    ]=  Special_effects_127    ;                          
		partList["Special_effects_127__2"     ]=  Special_effects_127     ;                         
		partList["Special_effects_127__20"    ]=  Special_effects_127    ;                          
		partList["Special_effects_127__21"    ]=  Special_effects_127    ;                          
		partList["Special_effects_127__22"    ]=  Special_effects_127    ;                          
		partList["Special_effects_127__23"    ]=  Special_effects_127    ;                          
		partList["Special_effects_127__24"    ]=  Special_effects_127    ;                          
		partList["Special_effects_127__25"    ]=  Special_effects_127    ;                          
		partList["Special_effects_127__26"    ]=  Special_effects_127    ;                          
		partList["Special_effects_127__27"    ]=  Special_effects_127    ;                          
		partList["Special_effects_127__28"    ]=  Special_effects_127    ;                          
		partList["Special_effects_127__29"    ]=  Special_effects_127    ;                          
		partList["Special_effects_127__3"     ]=  Special_effects_127     ;                         
		partList["Special_effects_127__30"    ]=  Special_effects_127    ;                          
		partList["Special_effects_127__31"    ]=  Special_effects_127    ;                          
		partList["Special_effects_127__32"    ]=  Special_effects_127    ;                          
		partList["Special_effects_127__33"    ]=  Special_effects_127    ;                          
		partList["Special_effects_127__34"    ]=  Special_effects_127    ;                          
		partList["Special_effects_127__35"    ]=  Special_effects_127    ;                          
		partList["Special_effects_127__36"    ]=  Special_effects_127    ;                          
		partList["Special_effects_127__37"    ]=  Special_effects_127    ;                          
		partList["Special_effects_127__38"    ]=  Special_effects_127    ;                          
		partList["Special_effects_127__39"    ]=  Special_effects_127    ;                          
		partList["Special_effects_127__4"     ]=  Special_effects_127     ;                         
		partList["Special_effects_127__40"    ]=  Special_effects_127    ;                          
		partList["Special_effects_127__41"    ]=  Special_effects_127    ;                          
		partList["Special_effects_127__42"    ]=  Special_effects_127    ;                          
		partList["Special_effects_127__47"    ]=  Special_effects_127    ;                          
		partList["Special_effects_127__48"    ]=  Special_effects_127    ;                          
		partList["Special_effects_127__5"     ]=  Special_effects_127     ;                         
		partList["Special_effects_127__50"    ]=  Special_effects_127    ;                          
		partList["Special_effects_127__52"    ]=  Special_effects_127    ;                          
		partList["Special_effects_127__6"     ]=  Special_effects_127     ;                         
		partList["Special_effects_127__7"     ]=  Special_effects_127     ;                         
		partList["Special_effects_127__8"     ]=  Special_effects_127     ;                         
		partList["Special_effects_127__9"     ]=  Special_effects_127     ;                         
		partList["Special_effects_160"        ]=  Special_effects_160        ;                      
		partList["Special_effects_161"        ]=  Special_effects_161        ;                      
		partList["Special_effects_162"        ]=  Special_effects_162        ;                      
		partList["TINY_Arm_Back_Lower_01"     ]=  TINY_Arm_Back_Lower_01     ;                         
		partList["TINY_Arm_Back_Lower_01__46" ]=  TINY_Arm_Back_Lower_01 ;                             
		partList["TINY_Arm_Back_Lower_01__6"  ]=  TINY_Arm_Back_Lower_01  ;                            
		partList["TINY_Arm_Back_Lower_02"     ]=  TINY_Arm_Back_Lower_02     ;                         
		partList["TINY_Arm_Back_Upper_01"     ]=  TINY_Arm_Back_Upper_01     ;                         
		partList["TINY_Arm_Back_Upper_01__5"  ]=  TINY_Arm_Back_Upper_01  ;                            
		partList["TINY_Arm_Top_Lower_01"      ]=  TINY_Arm_Top_Lower_01      ;                        
		partList["TINY_Arm_Top_Lower_01__1"   ]=  TINY_Arm_Top_Lower_01   ;                           
		partList["TINY_Arm_Top_Lower_01__2"   ]=  TINY_Arm_Top_Lower_01   ;                           
		partList["TINY_Arm_Top_Lower_01__3"   ]=  TINY_Arm_Top_Lower_01   ;                           
		partList["TINY_Arm_Top_Lower_01__45"  ]=  TINY_Arm_Top_Lower_01  ;                            
		partList["TINY_Arm_Top_Lower_02"      ]=  TINY_Arm_Top_Lower_02      ;                        
		partList["TINY_Arm_Top_Lower_03"      ]=  TINY_Arm_Top_Lower_03      ;                        
		partList["TINY_Arm_Top_Lower_04"      ]=  TINY_Arm_Top_Lower_04      ;                        
		partList["TINY_Arm_Top_Upper_01"      ]=  TINY_Arm_Top_Upper_01      ;                        
		partList["TINY_Arm_Top_Upper_01__1"   ]=  TINY_Arm_Top_Upper_01   ;                           
		partList["TINY_Head_01"               ]=  TINY_Head_01               ;               
		partList["TINY_Head_02"               ]=  TINY_Head_02               ;               
		partList["TINY_Head_03"               ]=  TINY_Head_03               ;               
		partList["TINY_Head_04"               ]=  TINY_Head_04               ;               
		partList["TINY_Head_05"               ]=  TINY_Head_05               ;               
		partList["TINY_Leg_Back_Lower_01"     ]=  TINY_Leg_Back_Lower_01     ;                         
		partList["TINY_Leg_Back_Lower_02"     ]=  TINY_Leg_Back_Lower_02     ;                         
		partList["TINY_Leg_Back_Upper_01"     ]=  TINY_Leg_Back_Upper_01     ;                         
		partList["TINY_Leg_Top_Lower_01"      ]=  TINY_Leg_Top_Lower_01      ;                        
		partList["TINY_Leg_Top_Lower_02"      ]=  TINY_Leg_Top_Lower_02      ;                        
		partList["TINY_Leg_Top_Upper_01"      ]=  TINY_Leg_Top_Upper_01      ;                        
		partList["TINY_Tail_01"               ]=  TINY_Tail_01               ;               
		partList["TINY_Torso_01"              ]=  TINY_Torso_01              ;                
		partList["TINY_Torso_02"              ]=  TINY_Torso_02              ;                
		partList["TINY_Weapon_01"             ]=  TINY_Weapon_01             ;                 
		partList["TINY_Weapon_02"             ]=  TINY_Weapon_02             ;                 
		partList["TINY_Weapon_02__4"          ]=  TINY_Weapon_02          ;                    
		partList["TINY_Weapon_02__7"          ]=  TINY_Weapon_02          ;                    
		partList["TINY_Weapon_03"             ]=  TINY_Weapon_03             ;                 
		partList["TINY_Weapon_03__10"         ]=  TINY_Weapon_03         ;                     
		partList["TINY_Weapon_03__11"         ]=  TINY_Weapon_03         ;                     
		partList["TINY_Weapon_04"             ]=  TINY_Weapon_04             ;                 
		partList["TINY_Weapon_04__9"          ]=  TINY_Weapon_04          ;                    
		partList["TINY_Weapon_05"             ]=  TINY_Weapon_05             ;                 
		partList["TINY_Weapon_05__8"          ]=  TINY_Weapon_05          ;                    
		partList["TINY_Weapon_06"             ]=  TINY_Weapon_06             ;                 
		partList["TINY_Weapon_07"             ]=  TINY_Weapon_07             ;                 
		partList["TINY_Weapon_08"             ]=  TINY_Weapon_08             ;                 
		partList["TINY_Weapon_09"             ]=  TINY_Weapon_09             ;                 
		partList["TINY_Weapon_10"             ]=  TINY_Weapon_10             ;                 
		partList["TINY_Weapon_10__2"          ]=  TINY_Weapon_10          ;                    
		partList["drop_shadow"                ]=  drop_shadow                ;              
				
				
				
				
				
//		partList["Antitank_Grenade_02"       ]= Antitank_Grenade_02         ;                                    
//		partList["Prop_01"                  ]= Prop_01                    ;    
//		partList["Prop_02"                  ]= Prop_02                    ;    
//		partList["Prop_02__2"               ]= Prop_02                    ;          
//		partList["Prop_02__3"               ]= Prop_02                    ;          
//		partList["Prop_03"                  ]= Prop_03                    ;    
//		partList["Prop_04"                  ]= Prop_04                    ;    
//		partList["Prop_05"                  ]= Prop_05                    ;    
//		partList["Prop_06"                  ]= Prop_06                    ;    
//		partList["Prop_06__1"               ]= Prop_06                    ;          
//		partList["Prop_06__3"               ]= Prop_06                    ;          
//		partList["Prop_06__4"               ]= Prop_06                    ;          
//		partList["Prop_07"                  ]= Prop_07                    ;    
//		partList["Prop_08"                  ]= Prop_08                    ;    
//		partList["Prop_09"                  ]= Prop_09                    ;    
//		partList["Special_Effects_84"        ]= Special_Effects_84          ;                        
//		partList["Special_Effects_84__2"     ]= Special_Effects_84          ;                              
//		partList["TINY_Arm_Back_Lower_01"   ]= TINY_Arm_Back_Lower_01     ;                                  
//		partList["TINY_Arm_Back_Lower_01__6"]= TINY_Arm_Back_Lower_01     ;                                        
//		partList["TINY_Arm_Back_Upper_01"   ]= TINY_Arm_Back_Upper_01     ;                                  
//		partList["TINY_Arm_Back_Upper_01__5"]= TINY_Arm_Back_Upper_01     ;                                        
//		partList["TINY_Arm_Top_Lower_01"    ]= TINY_Arm_Top_Lower_01      ;                                
//		partList["TINY_Arm_Top_Lower_01__1" ]= TINY_Arm_Top_Lower_01      ;                                      
//		partList["TINY_Arm_Top_Lower_01__2" ]= TINY_Arm_Top_Lower_01      ;                                      
//		partList["TINY_Arm_Top_Lower_01__3" ]= TINY_Arm_Top_Lower_01      ;                                      
//		partList["TINY_Arm_Top_Lower_02"    ]= TINY_Arm_Top_Lower_02      ;                                
//		partList["TINY_Arm_Top_Lower_03"    ]= TINY_Arm_Top_Lower_03      ;                                
//		partList["TINY_Arm_Top_Lower_04"    ]= TINY_Arm_Top_Lower_04      ;                                
//		partList["TINY_Arm_Top_Upper_01"    ]= TINY_Arm_Top_Upper_01      ;                                
//		partList["TINY_Arm_Top_Upper_01__1" ]= TINY_Arm_Top_Upper_01      ;                                      
//		partList["TINY_Head_01"             ]= TINY_Head_01               ;              
//		partList["TINY_Head_02"             ]= TINY_Head_02               ;              
//		partList["TINY_Head_03"             ]= TINY_Head_03               ;              
//		partList["TINY_Head_04"             ]= TINY_Head_04               ;              
//		partList["TINY_Head_05"             ]= TINY_Head_05               ;              
//		partList["TINY_Leg_Back_Lower_01"   ]= TINY_Leg_Back_Lower_01     ;                                  
//		partList["TINY_Leg_Back_Lower_02"   ]= TINY_Leg_Back_Lower_02     ;                                  
//		partList["TINY_Leg_Back_Upper_01"   ]= TINY_Leg_Back_Upper_01     ;                                  
//		partList["TINY_Leg_Top_Lower_01"    ]= TINY_Leg_Top_Lower_01      ;                                
//		partList["TINY_Leg_Top_Lower_02"    ]= TINY_Leg_Top_Lower_02      ;                                
//		partList["TINY_Leg_Top_Upper_01"    ]= TINY_Leg_Top_Upper_01      ;                                
//		partList["TINY_Tail_01"             ]= TINY_Tail_01               ;              
//		partList["TINY_Torso_01"            ]= TINY_Torso_01              ;                
//		partList["TINY_Torso_02"            ]= TINY_Torso_02              ;                
//		partList["TINY_Weapon_01"           ]= TINY_Weapon_01             ;                  
//		partList["TINY_Weapon_02"           ]= TINY_Weapon_02             ;                  
//		partList["TINY_Weapon_02__4"        ]= TINY_Weapon_02             ;                        
//		partList["TINY_Weapon_02__7"        ]= TINY_Weapon_02             ;                        
//		partList["TINY_Weapon_03"           ]= TINY_Weapon_03             ;                  
//		partList["TINY_Weapon_03__10"       ]= TINY_Weapon_03             ;                          
//		partList["TINY_Weapon_03__11"       ]= TINY_Weapon_03             ;                          
//		partList["TINY_Weapon_04"           ]= TINY_Weapon_04             ;                  
//		partList["TINY_Weapon_04__9"        ]= TINY_Weapon_04             ;                        
//		partList["TINY_Weapon_05"           ]= TINY_Weapon_05             ;                  
//		partList["TINY_Weapon_05__8"        ]= TINY_Weapon_05             ;                        
//		partList["drop_shadow"              ]= drop_shadow                ;   
//		
//		partList ["Antitank_grenade_03"]=Antitank_grenade_03;
//partList ["Antitank_grenade_03__49"]=Antitank_grenade_03;
//partList ["Antitank_grenade_03__51"]=Antitank_grenade_03;
//partList ["Antitank_grenade_03__53"]=Antitank_grenade_03;
//partList ["Special_effects_125"]=Special_effects_125;
//partList ["Special_effects_125__43"]=Special_effects_125;
//partList ["Special_effects_125__44"]=Special_effects_125;
//partList ["Special_effects_127"]=Special_effects_127;
//partList ["Special_effects_127__1"]=Special_effects_127;
//partList ["Special_effects_127__10"]=Special_effects_127;
//partList ["Special_effects_127__11"]=Special_effects_127;
//partList ["Special_effects_127__12"]=Special_effects_127;
//partList ["Special_effects_127__13"]=Special_effects_127;
//partList ["Special_effects_127__14"]=Special_effects_127;
//partList ["Special_effects_127__15"]=Special_effects_127;
//partList ["Special_effects_127__16"]=Special_effects_127;
//partList ["Special_effects_127__17"]=Special_effects_127;
//partList ["Special_effects_127__18"]=Special_effects_127;
//partList ["Special_effects_127__19"]=Special_effects_127;
//partList ["Special_effects_127__2"]=Special_effects_127;
//partList ["Special_effects_127__20"]=Special_effects_127;
//partList ["Special_effects_127__21"]=Special_effects_127;
//partList ["Special_effects_127__22"]=Special_effects_127;
//partList ["Special_effects_127__23"]=Special_effects_127;
//partList ["Special_effects_127__24"]=Special_effects_127;
//partList ["Special_effects_127__25"]=Special_effects_127;
//partList ["Special_effects_127__26"]=Special_effects_127;
//partList ["Special_effects_127__27"]=Special_effects_127;
//partList ["Special_effects_127__28"]=Special_effects_127;
//partList ["Special_effects_127__29"]=Special_effects_127;
//partList ["Special_effects_127__3"]=Special_effects_127;
//partList ["Special_effects_127__30"]=Special_effects_127;
//partList ["Special_effects_127__31"]=Special_effects_127;
//partList ["Special_effects_127__32"]=Special_effects_127;
//partList ["Special_effects_127__33"]=Special_effects_127;
//partList ["Special_effects_127__34"]=Special_effects_127;
//partList ["Special_effects_127__35"]=Special_effects_127;
//partList ["Special_effects_127__36"]=Special_effects_127;
//partList ["Special_effects_127__37"]=Special_effects_127;
//partList ["Special_effects_127__38"]=Special_effects_127;
//partList ["Special_effects_127__39"]=Special_effects_127;
//partList ["Special_effects_127__4"]=Special_effects_127;
//partList ["Special_effects_127__40"]=Special_effects_127;
//partList ["Special_effects_127__41"]=Special_effects_127;
//partList ["Special_effects_127__42"]=Special_effects_127;
//partList ["Special_effects_127__47"]=Special_effects_127;
//partList ["Special_effects_127__48"]=Special_effects_127;
//partList ["Special_effects_127__5"]=Special_effects_127;
//partList ["Special_effects_127__50"]=Special_effects_127;
//partList ["Special_effects_127__52"]=Special_effects_127;
//partList ["Special_effects_127__6"]=Special_effects_127;
//partList ["Special_effects_127__7"]=Special_effects_127;
//partList ["Special_effects_127__8"]=Special_effects_127;
//partList ["Special_effects_127__9"]=Special_effects_127;
//		partList ["TINY_Arm_Back_Lower_01__46"]=TINY_Arm_Back_Lower_01;
//		partList ["TINY_Arm_Top_Lower_01__45"]=TINY_Arm_Top_Lower_01;
//		partList ["TINY_Weapon_06"]=TINY_Weapon_06;
//		partList ["TINY_Weapon_07"]=TINY_Weapon_07;
//		partList ["TINY_Weapon_08"]=TINY_Weapon_08;
//		partList ["TINY_Weapon_09"]=TINY_Weapon_09;
	}
}
