using UnityEngine;
using System.Collections;

public class BoneStarLord : PieceAnimation
{
//	public GameObject Light2_w                   ;                
//	public GameObject SMALL_Accessory_Back_01    ;                               
//	public GameObject SMALL_Accessory_Front_01   ;                                
//	public GameObject SMALL_Arm_Back_Lower_01    ;                               
//	public GameObject SMALL_Arm_Back_Lower_02    ;                               
//	public GameObject SMALL_Arm_Back_Upper_01    ;                               
//	public GameObject SMALL_Arm_Top_Hand_01      ;                             
//	public GameObject SMALL_Arm_Top_Lower_01     ;                              
//	public GameObject SMALL_Arm_Top_Lower_02     ;                              
//	public GameObject SMALL_Arm_Top_Lower_04     ;                              
//	public GameObject SMALL_Arm_Top_Upper_01     ;                              
//	public GameObject SMALL_Arm_Top_Upper_02     ;                              
//	public GameObject SMALL_Arm_Top_Walkie_01    ;                              
//	public GameObject SMALL_Arm_Top_Walkie_02    ;                              
//	public GameObject SMALL_Arm_Top_Walkie_03    ;                               
//	public GameObject SMALL_Arm_Top_Walkie_04    ;                               
//	public GameObject SMALL_Head_01              ;                     
//	public GameObject SMALL_Head_02              ;                     
//	public GameObject SMALL_Head_03              ;                     
//	public GameObject SMALL_Head_04              ;                     
//	public GameObject SMALL_Leg_Back_Lower_01    ;                               
//	public GameObject SMALL_Leg_Back_Upper_01    ;                               
//	public GameObject SMALL_Leg_Top_Lower_01     ;                              
//	public GameObject SMALL_Leg_Top_Upper_01     ;                              
//	public GameObject SMALL_Light2_1             ;                      
//	public GameObject SMALL_Torso_01             ;                      
//	public GameObject SMALL_Torso_02             ;                      
//	public GameObject SMALL_Weapon_01            ;                       
//	public GameObject SMALL_Weapon_02            ;                       
//	public GameObject SMALL_Weapon_03            ;                       
//	public GameObject drop_shadow                ;                   
//	public GameObject light_4                    ;               
//	public GameObject light_6                    ;               
	
    public GameObject Light2_w                    ;
    public GameObject Light2k                     ;
    public GameObject SMALL_Accessory_Back_01     ;
    public GameObject SMALL_Accessory_Front_01    ;
    public GameObject SMALL_Arm_Back_Lower_01     ;
    public GameObject SMALL_Arm_Back_Lower_02     ;
    public GameObject SMALL_Arm_Back_Upper_01     ;
    public GameObject SMALL_Arm_Top_Hand_01       ;
    public GameObject SMALL_Arm_Top_Lower_01      ;
    public GameObject SMALL_Arm_Top_Lower_02      ;
    public GameObject SMALL_Arm_Top_Lower_04      ;
    public GameObject SMALL_Arm_Top_Upper_01      ;
    public GameObject SMALL_Arm_Top_Upper_02      ;
    public GameObject SMALL_Arm_Top_Walkie_01     ;
    public GameObject SMALL_Arm_Top_Walkie_02     ;
    public GameObject SMALL_Arm_Top_Walkie_03     ;
    public GameObject SMALL_Arm_Top_Walkie_04     ;
    public GameObject SMALL_Head_01               ;
    public GameObject SMALL_Head_02               ;
    public GameObject SMALL_Head_03               ;
    public GameObject SMALL_Head_04               ;
    public GameObject SMALL_Leg_Back_Lower_01     ;
    public GameObject SMALL_Leg_Back_Upper_01     ;
    public GameObject SMALL_Leg_Top_Lower_01      ;
    public GameObject SMALL_Leg_Top_Upper_01      ;
    public GameObject SMALL_Light2_1              ;
    public GameObject SMALL_Torso_01              ;
    public GameObject SMALL_Torso_02              ;
    public GameObject SMALL_Weapon_01             ;
    public GameObject SMALL_Weapon_02             ;
    public GameObject SMALL_Weapon_03             ;
    public GameObject SMALL_Weapon_04             ;
    public GameObject drop_shadow                 ;
	public GameObject fire_001                    ;
    public GameObject light_4                     ;
    public GameObject light_4k                    ;
    public GameObject light_6                     ;
    public GameObject light_6k                    ;
	public GameObject box_1a;
	public GameObject box_1b;
	public GameObject box_1c;
	public GameObject box_1d;
	public GameObject box_1e;
	
	public GameObject Light2_1u;
	public GameObject SMALL_Head_05;
	public GameObject SMALL_Weapon_08;
	
	// Use this for initialization
	public override void Awake ()
	{
		base.Awake ();
	}
	
	// Update is called once per frame
	protected override void initPartData ()
	{
		partList = new Hashtable ();
		
		partList ["Light2_w"] =                    Light2_w;        
        partList ["Light2_w1"] =                   Light2_w;       
        partList ["Light2k"] =                     Light2k;         
        partList ["Light2k__1"] =                  Light2k;      
        partList ["SMALL_Accessory_Back_01"] =     SMALL_Accessory_Back_01;                         
        partList ["SMALL_Accessory_Front_01"] =    SMALL_Accessory_Front_01;                         
        partList ["SMALL_Accessory_Front_011"] =   SMALL_Accessory_Front_01;                         
        partList ["SMALL_Accessory_Front_0110"] =  SMALL_Accessory_Front_01;                         
        partList ["SMALL_Accessory_Front_01__1"] = SMALL_Accessory_Front_01;                         
        partList ["SMALL_Accessory_Front_01__11"] =SMALL_Accessory_Front_01;                         
        partList ["SMALL_Arm_Back_Lower_01"] =     SMALL_Arm_Back_Lower_01;                    
        partList ["SMALL_Arm_Back_Lower_02"] =     SMALL_Arm_Back_Lower_02;                    
        partList ["SMALL_Arm_Back_Upper_01"] =     SMALL_Arm_Back_Upper_01;                    
        partList ["SMALL_Arm_Top_Hand_01"] =       SMALL_Arm_Top_Hand_01;                    
        partList ["SMALL_Arm_Top_Lower_01"] =      SMALL_Arm_Top_Lower_01;                    
        partList ["SMALL_Arm_Top_Lower_02"] =      SMALL_Arm_Top_Lower_02;                    
        partList ["SMALL_Arm_Top_Lower_04"] =      SMALL_Arm_Top_Lower_04;                    
        partList ["SMALL_Arm_Top_Upper_01"] =      SMALL_Arm_Top_Upper_01;                    
        partList ["SMALL_Arm_Top_Upper_02"] =      SMALL_Arm_Top_Upper_02;                    
        partList ["SMALL_Arm_Top_Walkie_01"] =     SMALL_Arm_Top_Walkie_01;                    
        partList ["SMALL_Arm_Top_Walkie_02"] =     SMALL_Arm_Top_Walkie_02;                    
        partList ["SMALL_Arm_Top_Walkie_03"] =     SMALL_Arm_Top_Walkie_03;                    
        partList ["SMALL_Arm_Top_Walkie_04"] =     SMALL_Arm_Top_Walkie_04;                    
        partList ["SMALL_Head_01"] =               SMALL_Head_01;                    
        partList ["SMALL_Head_02"] =               SMALL_Head_02;                    
        partList ["SMALL_Head_03"] =               SMALL_Head_03;                    
        partList ["SMALL_Head_04"] =               SMALL_Head_04;                    
        partList ["SMALL_Leg_Back_Lower_01"] =     SMALL_Leg_Back_Lower_01;                    
        partList ["SMALL_Leg_Back_Upper_01"] =     SMALL_Leg_Back_Upper_01;                    
        partList ["SMALL_Leg_Top_Lower_01"] =      SMALL_Leg_Top_Lower_01;                    
        partList ["SMALL_Leg_Top_Upper_01"] =      SMALL_Leg_Top_Upper_01;                    
        partList ["SMALL_Light2_1"] =              SMALL_Light2_1;                    
        partList ["SMALL_Light2_11"] =             SMALL_Light2_1;                    
        partList ["SMALL_Torso_01"] =              SMALL_Torso_01;                    
        partList ["SMALL_Torso_02"] =              SMALL_Torso_02;                    
        partList ["SMALL_Weapon_01"] =             SMALL_Weapon_01;                    
        partList ["SMALL_Weapon_0112"] =           SMALL_Weapon_01;                    
        partList ["SMALL_Weapon_013"] =            SMALL_Weapon_01;                    
        partList ["SMALL_Weapon_01__13"] =         SMALL_Weapon_01;                    
        partList ["SMALL_Weapon_02"] =             SMALL_Weapon_02;                    
        partList ["SMALL_Weapon_0211"] =           SMALL_Weapon_02;                    
        partList ["SMALL_Weapon_03"] =             SMALL_Weapon_03;                    
        partList ["SMALL_Weapon_032"] =            SMALL_Weapon_03;                    
        partList ["SMALL_Weapon_04"] =             SMALL_Weapon_04;                    
        partList ["SMALL_Weapon_04__12"] =         SMALL_Weapon_04;                    
        partList ["drop_shadow"] =                 drop_shadow;    
        partList ["fire_001"] =                    fire_001;
        partList ["fire_001__9"] =                 fire_001;
        partList ["light_4"] =                     light_4;         
        partList ["light_42"] =                    light_4;         
        partList ["light_43"] =                    light_4;         
        partList ["light_44"] =                    light_4;         
        partList ["light_45"] =                    light_4;         
        partList ["light_46"] =                    light_4;         
        partList ["light_47"] =                    light_4;         
        partList ["light_48"] =                    light_4;         
        partList ["light_4k"] =                    light_4k;         
        partList ["light_4k__2"] =                 light_4k;         
        partList ["light_4k__3"] =                 light_4k;         
        partList ["light_4k__4"] =                 light_4k;         
        partList ["light_4k__5"] =                 light_4k;         
        partList ["light_4k__6"] =                 light_4k;         
        partList ["light_4k__7"] =                 light_4k;         
        partList ["light_4k__8"] =                 light_4k;         
        partList ["light_6"] =                     light_6;         
        partList ["light_69"] =                    light_6;         
        partList ["light_6k"] =                    light_6k;         
        partList ["light_6k__10"] =                light_6k;   
		 partList ["box_1a"]=box_1a;
		 partList ["box_1b"]=box_1b;
		 partList ["box_1c"]=box_1c;
		 partList ["box_1d"]=box_1d;
		 partList ["box_1e"]=box_1e;
		
		partList ["Light2_1u"]=Light2_1u;
		partList ["Light2_1u__1"]=Light2_1u;
		partList ["SMALL_Head_05"]=SMALL_Head_05;
		partList ["SMALL_Weapon_01__4"]=SMALL_Weapon_01;
		partList ["SMALL_Weapon_08"]=SMALL_Weapon_08;
		partList ["SMALL_Weapon_08__3"]=SMALL_Weapon_08;
		partList ["SMALL_Accessory_Front_01__2"]=SMALL_Accessory_Front_01;
		
				
//		partList ["Light2_w"] =                                          Light2_w;                 
//		partList ["Light2_w1"] =                                         Light2_w;                
//		partList ["SMALL_Accessory_Back_01"] =                           SMALL_Accessory_Back_01;  
//		partList ["SMALL_Accessory_Front_01"] =                          SMALL_Accessory_Front_01; 
//		partList ["SMALL_Accessory_Front_011"] =                         SMALL_Accessory_Front_01;
//		partList ["SMALL_Accessory_Front_0110"] =                        SMALL_Accessory_Front_01;
//		partList ["SMALL_Accessory_Front_01__1"] =                        SMALL_Accessory_Front_01;
//		partList ["SMALL_Arm_Back_Lower_01"] =                           SMALL_Arm_Back_Lower_01;  
//		partList ["SMALL_Arm_Back_Lower_02"] =                           SMALL_Arm_Back_Lower_02;  
//		partList ["SMALL_Arm_Back_Upper_01"] =                           SMALL_Arm_Back_Upper_01;  
//		partList ["SMALL_Arm_Top_Hand_01"] =                             SMALL_Arm_Top_Hand_01;
//		partList ["SMALL_Arm_Top_Lower_01"] =                            SMALL_Arm_Top_Lower_01;   
//		partList ["SMALL_Arm_Top_Lower_02"] =                            SMALL_Arm_Top_Lower_02;   
//		partList ["SMALL_Arm_Top_Lower_04"] =                            SMALL_Arm_Top_Lower_04; 
//		partList ["SMALL_Arm_Top_Upper_01"] =                            SMALL_Arm_Top_Upper_01;   
//		partList ["SMALL_Arm_Top_Upper_02"] =                            SMALL_Arm_Top_Upper_02;   
//		partList ["SMALL_Arm_Top_Walkie_01"] =                           SMALL_Arm_Top_Walkie_01;   
//		partList ["SMALL_Arm_Top_Walkie_02"] =                           SMALL_Arm_Top_Walkie_02;   
//		partList ["SMALL_Arm_Top_Walkie_03"] =                           SMALL_Arm_Top_Walkie_03;   
//		partList ["SMALL_Arm_Top_Walkie_04"] =                           SMALL_Arm_Top_Walkie_04;   
//		partList ["SMALL_Head_01"] =                                     SMALL_Head_01;            
//		partList ["SMALL_Head_02"] =                                     SMALL_Head_02;            
//		partList ["SMALL_Head_03"] =                                     SMALL_Head_03;             
//		partList ["SMALL_Head_04"] =                                     SMALL_Head_04;           
//		partList ["SMALL_Leg_Back_Lower_01"] =                           SMALL_Leg_Back_Lower_01;  
//		partList ["SMALL_Leg_Back_Upper_01"] =                           SMALL_Leg_Back_Upper_01;  
//		partList ["SMALL_Leg_Top_Lower_01"] =                            SMALL_Leg_Top_Lower_01;   
//		partList ["SMALL_Leg_Top_Upper_01"] =                            SMALL_Leg_Top_Upper_01;   
//		partList ["SMALL_Light2_1"] =                                    SMALL_Light2_1;           
//		partList ["SMALL_Light2_11"] =                                   SMALL_Light2_1;          
//		partList ["SMALL_Torso_01"] =                                    SMALL_Torso_01;           
//		partList ["SMALL_Torso_02"] =                                    SMALL_Torso_02;           
//		partList ["SMALL_Weapon_01"] =                                   SMALL_Weapon_01;          
//		partList ["SMALL_Weapon_0112"] =                                 SMALL_Weapon_01;        
//		partList ["SMALL_Weapon_013"] =                                  SMALL_Weapon_01;        
//		partList ["SMALL_Weapon_02"] =                                   SMALL_Weapon_02;         
//		partList ["SMALL_Weapon_0211"] =                                 SMALL_Weapon_02;        
//		partList ["SMALL_Weapon_03"] =                                   SMALL_Weapon_03;         
//		partList ["SMALL_Weapon_032"] =                                  SMALL_Weapon_03;        
//		partList ["drop_shadow"] =                                       drop_shadow;             
//		partList ["light_4"] =                                           light_4;                 
//		partList ["light_42"] =                                          light_4;                
//		partList ["light_43"] =                                          light_4;                
//		partList ["light_44"] =                                          light_4;                
//		partList ["light_45"] =                                          light_4;                
//		partList ["light_46"] =                                          light_4;                
//		partList ["light_47"] =                                          light_4;                
//		partList ["light_48"] =                                          light_4;                
//		partList ["light_6"] =                                           light_6;                 
//		partList ["light_69"] =                                          light_6;                
	}
}
